site_name: Documentação do OneDb
theme: material  

plugins:
  - search  
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.insert(0, 'C:\\Users\\SE60731\\Documents\\Estudos\\onedb') 
nav:
    - Início: index.md
    - API: api.md

